version: '3.1'

services:
  db:
    build: .
    container_name: todo-db
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo